apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: confluent
spec:
  replicas: 1
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:13
        ports:
          - name: tpc
            protocol: TCP
            containerPort: 5432
        envFrom:
          - configMapRef:
               name: postgres-config
        volumeMounts:
          - name: postgresvol
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresvol
        persistentVolumeClaim:
          claimName: local-volume-pvc-postgresql
