apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-pvc-postgresql
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
