logging:
  level:
    root: INFO
    com.provectus: INFO
    org.springframework.http.codec.json.Jackson2JsonEncoder: INFO
    #org.springframework.http.codec.json.Jackson2JsonDecoder: DEBUG
    reactor.netty.http.server.AccessLog: INFO

server:
  port: 18080

kafka:
  clusters:
    - name: local
      bootstrapServers: tester101.young.com:9092,tester102.young.com:9092,tester103.young.com:9092
      properties: 
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: GSSAPI
        sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/app/kafka-ui/confluent_c3.keytab" principal="confluent_c3@KAFKA.SECURE";   
        sasl.kerberos.service.name: kafka
      zookeeper: tester101.young.com:2181,tester102.young.com:2181,tester103.young.com:2181
      schemaRegistry: http://tester101.young.com:8081
      metrics:
        port: 7071
        type: PROMETHEUS
  #    -
  #      name: secondLocal
  #      bootstrapServers: localhost:9093
  #      zookeeper: localhost:2182
  #      schemaRegistry: http://localhost:18085
  #      kafkaConnect:
  #        - name: first
  #          address: http://localhost:8083
  #      metrics:
  #        port: 9998
  #        type: JMX
  #      read-only: true
  #    -
  #      name: localUsingProtobufFile
  #      bootstrapServers: localhost:9092
  #      protobufFile: messages.proto
  #      protobufMessageName: GenericMessage
  #      protobufMessageNameByTopic:
  #        input-topic: InputMessage
  #        output-topic: OutputMessage
spring:
  jmx:
    enabled: true

auth:
  type: DISABLED
#  type: OAUTH2
#  oauth2:
#    client:
#      cognito:
#        clientId:
#        clientSecret:
#        scope: openid
#        client-name: cognito
#        provider: cognito
#        redirect-uri: http://localhost:8080/login/oauth2/code/cognito
#        authorization-grant-type: authorization_code
#        issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M7cIUn1nj
#        jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M7cIUn1nj/.well-known/jwks.json
#        user-name-attribute: username
#        custom-params:
#          type: cognito
#          logoutUrl: https://kafka-ui.auth.eu-central-1.amazoncognito.com/logout
#      google:
#        provider: google
#        clientId:
#        clientSecret:
#        user-name-attribute: email
#        custom-params:
#          type: google
#          allowedDomain: provectus.com
#      github:
#        provider: github
#        clientId:
#        clientSecret:
#        scope:
#          - read:org
#        user-name-attribute: login
#        custom-params:
#          type: github
