---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: datagen
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: pageviews
    quickstart: pageviews
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter.schemas.enable: "False"
    max.interval: "1000"
    iterations: "10000"
