---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: datagen-avro
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: users
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081" 
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    quickstart: "users"
    max.interval: "1000"
    iterations: "10000"
