apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: mysqlcdc01.cdctest.contents
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name:  mysqlcdc01.cdctest.history
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
