apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: payment-value
  namespace: confluent
spec:
  compatibilityLevel: FULL
  data:
    configRef: payment-schema-config 
    format: avro
  schemaRegistryRest: 
    endpoint: http://schemaregistry.confluent.svc.cluster.local:8081 
