download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/confluent-platform-7.5.2.tar.gz
format_version: 1.0.0
name: platform
namespace: confluent
server: https://galaxy.ansible.com/api/
signatures: []
version: 7.5.2
version_url: /api/v3/plugin/ansible/content/published/collections/index/confluent/platform/versions/7.5.2/
